import tkinter as tk
import subprocess
from tkinter import messagebox

def compile_latex():
    latex_code = text.get(1.0, tk.END)
    
    # Create a temporary LaTeX file
    with open('temp.tex', 'w') as f:
        f.write(latex_code)
    
    # Specify the full path to pdflatex
    pdflatex_path = r'D:\mikTex\miktex\bin\x64\pdflatex.exe'  # Replace with the actual path to pdflatex
    
    # Compile the LaTeX file using pdflatex
    subprocess.call([pdflatex_path, 'temp.tex'])
    
    # Remove unnecessary files generated by pdflatex
    subprocess.call(['del', 'temp.aux', 'temp.log', 'temp.tex'])
    
    # Rename the resulting PDF file
    subprocess.call(['ren', 'temp.pdf', 'output.pdf'])
    
    # Display a success message
    messagebox.showinfo("Success", "PDF compiled successfully!")

# Create the main window
window = tk.Tk()
window.title("LaTeX Compiler")

# Create a text widget for entering LaTeX code
text = tk.Text(window, height=10, width=50)
text.pack()

# Create a button to compile LaTeX code
compile_button = tk.Button(window, text="Compile", command=compile_latex)
compile_button.pack()

# Run the main event loop
window.mainloop()
